apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuya-alarm-ingress
  labels:
    app: tuya-alarm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: tuya-alarm.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tuya-alarm-service
                port:
                  number: 5000